export {default as Home} from "./Home"
export {default as Activities} from "./Activities"
export {default as Login} from "./Login"
export {default as Signup} from "./Signup"
export {default as Intro} from "./Intro"
export {default as Discussions} from "./Discussions"
export {default as Game} from "./Game"